version: "3.9"
services:
  server:
    build:
      dockerfile: ./e2e/server/Dockerfile
      context: .
    networks:
      internet:
        ipv4_address: 10.100.1.4
    cap_add:
      - NET_ADMIN
  client0:
    build: 
      dockerfile: ./e2e/client/Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      - GATEWAY=172.31.0.2
    cap_add:
      - NET_ADMIN
    networks:
      peer0:
        ipv4_address: 172.31.0.3
    command: >
      -serverIp 10.100.1.4
  router0:
    build: ./e2e/router
    cap_add:
      - NET_ADMIN
    environment:
      - EXT_IP=10.100.1.4
      - SOURCE_IP=10.100.1.2
    networks:
      peer0:
        ipv4_address: 172.31.0.2
      internet:
        ipv4_address: 10.100.1.2
  client1:
    build:
      dockerfile: ./e2e/client/Dockerfile
      context: .
    cap_add:
      - NET_ADMIN
    networks:
      peer1:
        ipv4_address: 172.32.0.3
  router1:
    build: ./e2e/router
    cap_add:
      - NET_ADMIN
    environment:
      - EXT_IP=10.100.1.4
      - SOURCE_IP=10.100.1.3
    networks:
      peer1:
        ipv4_address: 172.32.0.2
      internet:
        ipv4_address: 10.100.1.3
networks:
  peer0:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24
  peer1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/24
  internet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.1.0/24